# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Language-Frink-Eval
version:      0.01
version_from: lib/Language/Frink/Eval.pm
installdirs:  site
requires:
    Params::Validate:              0.74

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
